### ISSUE TITLE
Timeline thumbnails are not rendering when using a remote url to a video

### ISSUE THREAD

**Issue by Catsvilles** [BabylonJS/Controls#45]
Works perfect with local files though. Anything we can do here?

**Comment by RaananW** [comment]
@sebavan - i assigned you but we can talk about this :-)

**Comment by sebavan** [comment]
This might be a cors issue ??? 

like your video not having the crossOrigin attribute set to anonymous for instance required by webgl to allow loading cross origin content ?

**Comment by Catsvilles** [comment]
I'm not sure, I tried many different URLs/servers, and didn't get obvious CORS errors, although there were some networking errors in the Network tab.

+Plus the example doesn't work in Safari even with local files. But that's a completely different issue I guess.

**Comment by sebavan** [comment]
Could you provide a repro cause it seems to work on the demo page which is using a remote url ?
