### ISSUE TITLE
The use of instanceof causes video element to be upside down

### ISSUE THREAD

**Issue by nerocui** [BabylonJS/Controls#48]
https://github.com/BabylonJS/Controls/blob/e06eb45aa1555a17c06f4b4dad5ad1d25e729d39/src/coreControls/elementToTexture.ts#L65

This code is used in flipgrid code to render the timeline component. In a child window where the global window object is not the correct one, this line fails and the feed becomes upside down. Similar to https://github.com/BabylonJS/Babylon.js/issues/13391 

<img width="447" alt="babylon_timeline_upsidedown" src="https://user-images.githubusercontent.com/10738280/221641121-02639d5d-7526-42bd-9c3a-c397ba70d784.png">

**Comment by sebavan** [comment]
Should be fixed by https://github.com/BabylonJS/Controls/commit/3407854de07f09ed621ba089e55bde2e108d3978
