### ISSUE TITLE
Timeline Images not showing on Edge

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Controls#8]
The images in the timeline are not showing (see screen shoot). Used the default version of Edge installed w/ Windows 10 (Microsoft Edge 44.18362.267.0).
![timeLine Edge Screenshot](https://user-images.githubusercontent.com/32072891/63280191-35b13b80-c25f-11e9-9ebc-a2c17555e293.png)

**Comment by sebavan** [comment]
Oh it looks like some of the es features in use for the demo are not compatible. It is only a demo issue the shipped version is ok, I ll fix it ASAP.

**Comment by thomlucc** [comment]
OK, got it. Perfect, thanks a lot!

**Comment by sebavan** [comment]
Fixed by https://github.com/BabylonJS/Controls/commit/9395a092dabb24a271b62fa7b6f5ac1672002e45
